[package]
name = "mezon-ui"
version.workspace = true
edition = "2024"

[lints]
workspace = true

[dependencies]
futures.workspace = true
gpui = { workspace = true, features = ["inspector"] }
ui.workspace = true
theme.workspace = true
icons.workspace = true
menu.workspace = true
mezon-store.workspace = true
mezon-video.workspace = true
mezon-audio.workspace = true
mezon-i18n.workspace = true
anyhow.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
chrono.workspace = true
flume.workspace = true
rust-embed.workspace = true
unicode-segmentation.workspace = true
unicode-normalization.workspace = true
indexmap.workspace = true
image.workspace = true
qrcode.workspace = true
smallvec.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
block = "0.1"
objc.workspace = true
raw-window-handle.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true
