[package]
name = "mezon-ui"
version.workspace = true
license.workspace = true
edition = "2024"

[lints]
workspace = true

[dependencies]
futures.workspace = true
gpui = { workspace = true, features = ["inspector"] }
ui.workspace = true
theme.workspace = true
icons.workspace = true
menu.workspace = true
mezon-store.workspace = true
mezon-canvas.workspace = true
mezon-theme.workspace = true
mezon-widgets.workspace = true
mezon-client.workspace = true
mezon-video.workspace = true
mezon-audio.workspace = true
mezon-voice.workspace = true
mezon-i18n.workspace = true
mezon-pdf.workspace = true
anyhow.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
chrono.workspace = true
flume.workspace = true
rust-embed.workspace = true
unicode-segmentation.workspace = true
unicode-normalization.workspace = true
indexmap.workspace = true
image.workspace = true
base64.workspace = true
qrcode.workspace = true
percent-encoding.workspace = true
smallvec.workspace = true
scap.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["inspector", "test-support"] }

[target.'cfg(target_os = "macos")'.dependencies]
block = "0.1"
objc.workspace = true
raw-window-handle.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
libc.workspace = true
raw-window-handle.workspace = true
scap = { workspace = true, features = ["wayland", "x11"] }
x11rb = { version = "0.13", features = ["allow-unsafe-code"] }

[target.'cfg(target_os = "windows")'.dependencies]
raw-window-handle.workspace = true
windows.workspace = true
