[package]
name = "mezon-video"
version.workspace = true
license.workspace = true
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc.workspace = true
core-foundation.workspace = true
core-foundation-sys.workspace = true
core-video.workspace = true

[target.'cfg(not(target_os = "macos"))'.dependencies]
gpui.workspace = true
image.workspace = true
smallvec.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
gstreamer = "0.23"
gstreamer-app = "0.23"
gstreamer-video = "0.23"
gdk-pixbuf = "0.20"

[target.'cfg(windows)'.dependencies]
windows-core.workspace = true
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Variant",
    "Win32_Media_MediaFoundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Imaging",
    "Win32_Storage_FileSystem",
] }
