[package]
name = "mezon-record"
version.workspace = true
license.workspace = true
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
parking_lot.workspace = true
flume.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc.workspace = true
core-foundation.workspace = true
core-foundation-sys.workspace = true
core-video.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
gstreamer = "0.23"
gstreamer-app = "0.23"
gstreamer-video = "0.23"

[target.'cfg(windows)'.dependencies]
yuv.workspace = true
windows-core.workspace = true
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_Variant",
    "Win32_Media_MediaFoundation",
    "Win32_Storage_FileSystem",
] }

[dev-dependencies]
tempfile.workspace = true
