[package]
name = "mezon-client"
version.workspace = true
license.workspace = true
edition = "2024"

[dependencies]
mezon-proto.workspace = true
tokio.workspace = true
tokio-rustls = { version = "0.26", features = ["ring"] }
tokio-tungstenite = { version = "0.29", default-features = false, features = ["connect", "rustls-tls-webpki-roots"] }
webpki-roots = "1.0.7"
http_client.workspace = true
reqwest_client.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
prost.workspace = true
image.workspace = true
keyring.workspace = true
dirs.workspace = true
base64.workspace = true
rand.workspace = true
url.workspace = true
percent-encoding.workspace = true
async-trait = "0.1"
flate2 = "1"
bytes.workspace = true
foyer.workspace = true
parking_lot.workspace = true
regex.workspace = true

[dev-dependencies]
proptest.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }

[target.'cfg(target_os = "macos")'.dependencies]
system-configuration = "0.6"
core-foundation = "0.9"

[target.'cfg(target_os = "windows")'.dependencies]
windows.workspace = true
